export const projects = [
  {
    title: 'Notes App',
    description: "This is a Simple React App with UI designed with Material-UI . It is fully responsive and also allows users to toggle between different modes.",
      image: '/images/1.png',
      tags: ['Material-UI',  'React'],
    source: 'https://github.com/Bhawukp/NotesApp.git',
    visit: 'https://notesbybp.netlify.app/',
    id: 0,
  },
  {
    title: 'Messaging-App',
    description:"It is simple messaging app UI powered with firebase and chatengine.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript','Chat-Engine','Firebase'],
    source: 'https://github.com/Bhawukp/ChatBox',
    visit: 'https://chatbox2.netlify.app/',
    id: 1,
  },
  {
    title: 'Tesla Clone',
    description: "A Simple React Native app that showcases Tesla cars like that in tesla official website.",
      image: '/images/3.jpg',
      tags: ['React-Native'],
    source: 'https://expo.dev/@bhawukp/teslaclone',
    visit: 'https://expo.dev/@bhawukp/teslaclonem',
    id: 2,
  },
  {
    title: 'Movies-app',
    description: "This project is a React project .It is a mordern UI design.It displays the movies with overview and ratings.",
    image: '/images/4.jpg',
    tags: ['React','Advanced CSS'],
    source: 'https://github.com/Bhawukp/React-Project',
    visit: 'https://bhawukp.github.io/React-Project/',
    id: 3,
  },
  {
    title: 'Netflix-clone',
    description: "Exploring more on React.js I designed a netflix-clone with almost same UI of the original netflix app .This app is capable of playing the trailer on YouTube as well.",
    image: '/images/4.jpg',
    tags: ['React','Advanced CSS','Netflix-Developer Tools'],
    source: 'https://jarvisdeveloper.netlify.app/',
    visit: 'https://jarvisdeveloper.netlify.app/',
    id: 4,
  },
  {
    title: 'Animations',
    description: " Creative Animations developed with the help of HTML CSS and many open source JavaScript libraries ",
    image: '/images/4.jpg',
    tags: ['HTML',' CSS','JavaScript'],
    source: 'https://github.com/Bhawukp/Animations',
    visit: 'https://github.com/Bhawukp/Animations',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Matriculated from Ryan International School, Chandigarh.' },
  { year: 2019, text: 'Completed intermediate from GMSSS 33, Chandigarh; began coding journey.' },
  { year: 2020, text: 'Joined Wipro–NASSCOM Future Skills program.' },
  { year: 2021, text: 'Shared projects online; joined Microsoft Azure Developer League.' },
  { year: 2022, text: 'Started career as Software Engineer Intern in media streaming domain.' },
  { year: 2023, text: 'Promoted to Software Engineer; built Smart TV and web apps using React.' },
  { year: 2024, text: 'Optimized app performance and user experience across platforms.' },
  { year: 2025, text: 'Exploring AI-assisted development and system design.' }
];